name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: run test
        run: python3 test_app.py

      - name: build docker image
        run: docker build -t myapp:${GITHUB_SHA} .

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run k8
        run: |
          sed -e "s/TAG/${GITHUB_SHA}/g" deploy.yml | kubectl apply -f -
          ls
          cat deploy.yml

